### ISSUE TITLE
error when opening the zip file

### ISSUE THREAD

**Issue by yugo2911** [Relepega/doujinstyle-downloader#9]
**Describe the bug**
windows default in-built archive tool gives error, 
7-zip works fine, so its windows archive tool issue... _small indie company_.  😄
btw i had same issue in previous releases aswell.

feel free to dont care about this, cuz alternative zipping software works.

**Screenshots**
![explorer_BfsI6P16Pg](https://github.com/user-attachments/assets/788a0929-ad29-4ca9-9333-58bae60272ca)

**Desktop (please complete the following information):**
 - OS: WIndows 11 24H2 (26100.1742)

**Comment by Relepega** [comment]
Hi, thanks for tracking this issue!

Personally I made 7zip my default archive opening app so I really didn't make sure this was an issue... but it is now fixed with the latest commit 0dd738ef9972e9c0911be41087acd711fcaa7177 (this time I did test it 😅).
This build tooling change will be applied from the next build onwards!
